version: "3.9"
services:
  app:
    image: golang:1.18.2-buster
    container_name: app
    ports: 
      - 9000:9000
    env_file:
      - DEV.env
    working_dir: /src/go-chat-signal-server
    volumes:
      - ./:/src/go-chat-signal-server
    depends_on:
      - redis
    command: go run cmd/httpserver/main.go

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data/redis-data

volumes:
  redis-data:
