// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/killtheverse/go-chat-signal-server/internal/core/services"
	"github.com/killtheverse/go-chat-signal-server/internal/handlers/httphandlers"
	"github.com/killtheverse/go-chat-signal-server/internal/repositories"
)

// Injectors from inject.go:

func InitializeUserHandlers(mongoURI repositories.ConnectionURI, mongoDBName repositories.DatabaseName) (*httphandlers.UserHandler, error) {
	userRepository, err := repositories.NewUserRepository(mongoURI, mongoDBName)
	if err != nil {
		return nil, err
	}
	userService := services.NewUserService(userRepository)
	userHandler := httphandlers.NewUserHandler(userService)
	return userHandler, nil
}
