package dataservice

import "github.com/killtheverse/go-chat-signal-server/model"

// UserDataInterface represents interface for user data access through database
type UserDataInterface interface {
    // Insert inserts the user in the database. The returned User has an ID which is auto generated by the database
    Insert(*model.User) (*model.User, error)
}
